// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.2
// source: grpc/protobuff/quiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQuestionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQuestionsRequest) Reset() {
	*x = ListQuestionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsRequest) ProtoMessage() {}

func (x *ListQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{0}
}

type ListQuestionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*ListQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *ListQuestionsResponse) Reset() {
	*x = ListQuestionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsResponse) ProtoMessage() {}

func (x *ListQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuestionsResponse) GetQuestions() []*ListQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type ListQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Question string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answers  []string `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *ListQuestion) Reset() {
	*x = ListQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestion) ProtoMessage() {}

func (x *ListQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestion.ProtoReflect.Descriptor instead.
func (*ListQuestion) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *ListQuestion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ListQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitQuizRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*SubmittedAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *SubmitQuizRequest) Reset() {
	*x = SubmitQuizRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizRequest) ProtoMessage() {}

func (x *SubmitQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizRequest.ProtoReflect.Descriptor instead.
func (*SubmitQuizRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitQuizRequest) GetAnswers() []*SubmittedAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmittedAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId  int32 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerIndex int32 `protobuf:"varint,2,opt,name=answer_index,json=answerIndex,proto3" json:"answer_index,omitempty"`
}

func (x *SubmittedAnswer) Reset() {
	*x = SubmittedAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmittedAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmittedAnswer) ProtoMessage() {}

func (x *SubmittedAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmittedAnswer.ProtoReflect.Descriptor instead.
func (*SubmittedAnswer) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *SubmittedAnswer) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *SubmittedAnswer) GetAnswerIndex() int32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

type SubmitQuizResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessRatePercentage float32 `protobuf:"fixed32,1,opt,name=success_rate_percentage,json=successRatePercentage,proto3" json:"success_rate_percentage,omitempty"`
	CorrectAnswers        int32   `protobuf:"varint,2,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	TotalQuestions        int32   `protobuf:"varint,3,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
}

func (x *SubmitQuizResponse) Reset() {
	*x = SubmitQuizResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protobuff_quiz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitQuizResponse) ProtoMessage() {}

func (x *SubmitQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protobuff_quiz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitQuizResponse.ProtoReflect.Descriptor instead.
func (*SubmitQuizResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protobuff_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitQuizResponse) GetSuccessRatePercentage() float32 {
	if x != nil {
		return x.SuccessRatePercentage
	}
	return 0
}

func (x *SubmitQuizResponse) GetCorrectAnswers() int32 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *SubmitQuizResponse) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

var File_grpc_protobuff_quiz_proto protoreflect.FileDescriptor

var file_grpc_protobuff_quiz_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66,
	0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6a, 0x61, 0x6d,
	0x6d, 0x33, 0x65, 0x33, 0x33, 0x33, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65,
	0x33, 0x33, 0x33, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x54, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x22, 0x56,
	0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65, 0x33, 0x33, 0x33,
	0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x22, 0x55, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x9e, 0x01,
	0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x15, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x61,
	0x74, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xe0,
	0x01, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x7a, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x2c, 0x2e, 0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65, 0x33, 0x33, 0x33, 0x33, 0x2e, 0x71, 0x75, 0x69,
	0x7a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e,
	0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65, 0x33, 0x33, 0x33, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x0a,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x29, 0x2e, 0x6a, 0x61, 0x6d,
	0x6d, 0x33, 0x65, 0x33, 0x33, 0x33, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65, 0x33, 0x33,
	0x33, 0x33, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6a, 0x61, 0x6d, 0x6d, 0x33, 0x65, 0x33, 0x33, 0x33, 0x33, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2d,
	0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpc_protobuff_quiz_proto_rawDescOnce sync.Once
	file_grpc_protobuff_quiz_proto_rawDescData = file_grpc_protobuff_quiz_proto_rawDesc
)

func file_grpc_protobuff_quiz_proto_rawDescGZIP() []byte {
	file_grpc_protobuff_quiz_proto_rawDescOnce.Do(func() {
		file_grpc_protobuff_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protobuff_quiz_proto_rawDescData)
	})
	return file_grpc_protobuff_quiz_proto_rawDescData
}

var file_grpc_protobuff_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_protobuff_quiz_proto_goTypes = []interface{}{
	(*ListQuestionsRequest)(nil),  // 0: jamm3e3333.quiz.api.v1.ListQuestionsRequest
	(*ListQuestionsResponse)(nil), // 1: jamm3e3333.quiz.api.v1.ListQuestionsResponse
	(*ListQuestion)(nil),          // 2: jamm3e3333.quiz.api.v1.ListQuestion
	(*SubmitQuizRequest)(nil),     // 3: jamm3e3333.quiz.api.v1.SubmitQuizRequest
	(*SubmittedAnswer)(nil),       // 4: jamm3e3333.quiz.api.v1.SubmittedAnswer
	(*SubmitQuizResponse)(nil),    // 5: jamm3e3333.quiz.api.v1.SubmitQuizResponse
}
var file_grpc_protobuff_quiz_proto_depIdxs = []int32{
	2, // 0: jamm3e3333.quiz.api.v1.ListQuestionsResponse.questions:type_name -> jamm3e3333.quiz.api.v1.ListQuestion
	4, // 1: jamm3e3333.quiz.api.v1.SubmitQuizRequest.answers:type_name -> jamm3e3333.quiz.api.v1.SubmittedAnswer
	0, // 2: jamm3e3333.quiz.api.v1.QuizService.ListQuestions:input_type -> jamm3e3333.quiz.api.v1.ListQuestionsRequest
	3, // 3: jamm3e3333.quiz.api.v1.QuizService.SubmitQuiz:input_type -> jamm3e3333.quiz.api.v1.SubmitQuizRequest
	1, // 4: jamm3e3333.quiz.api.v1.QuizService.ListQuestions:output_type -> jamm3e3333.quiz.api.v1.ListQuestionsResponse
	5, // 5: jamm3e3333.quiz.api.v1.QuizService.SubmitQuiz:output_type -> jamm3e3333.quiz.api.v1.SubmitQuizResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_protobuff_quiz_proto_init() }
func file_grpc_protobuff_quiz_proto_init() {
	if File_grpc_protobuff_quiz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protobuff_quiz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protobuff_quiz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protobuff_quiz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protobuff_quiz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitQuizRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protobuff_quiz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmittedAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protobuff_quiz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitQuizResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protobuff_quiz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protobuff_quiz_proto_goTypes,
		DependencyIndexes: file_grpc_protobuff_quiz_proto_depIdxs,
		MessageInfos:      file_grpc_protobuff_quiz_proto_msgTypes,
	}.Build()
	File_grpc_protobuff_quiz_proto = out.File
	file_grpc_protobuff_quiz_proto_rawDesc = nil
	file_grpc_protobuff_quiz_proto_goTypes = nil
	file_grpc_protobuff_quiz_proto_depIdxs = nil
}
