name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-docker-containers
        uses: docker/setup-buildx-action@v2

      - name: run-docker-containers
        run: make up-detached

      - name: run-tests
        run: make test
